### ISSUE TITLE
Upgrade to BotBuilder v3

### ISSUE THREAD

**Issue by Stevenic** [andrew-makarenko/botbuilder-facebook#2]
Hey there... Just wondering if you have plans to upgrade this to the new v3 SDK?  In the new SDK you're FacebookBot would become a FacebookConnector for the new UniversalBot class and it should be way simpler as all you have to do is the schema mapping work. The UniversalBot class does all of the session management now.  If you're up for doing the work to port your lib to the new connector model I'm happy to answer any questions and code review your final bits.

Steve

**Comment by andrew-makarenko** [comment]
Hey!
Yes, I'm going to support this library and will update it to support new v3 SDK later this week.
I will let you know if I need any help.
Thank you!

**Comment by Stevenic** [comment]
Thanks!

**Comment by iangriggs** [comment]
Hi @andrew-makarenko,

Wondered if you'd been already looking at this but haven't quite pushed up to GH yet? I'm asking as if you've not had a chance then I might attempt myself...just didn't want to duplicate any effort you might have already made. ;-)

Thanks!

**Comment by andrew-makarenko** [comment]
Hey!
I don't have enough time right now to support it, my bots projects were postponed.
I pushed v3 support to the new branch https://github.com/andrew-makarenko/botbuilder-facebook/tree/botbuilder3 but it works only for txt messages.

**Comment by iangriggs** [comment]
Hi,

Thanks for the update and for posting where you'd got to so far in a separate branch. 

I'll have a look myself as we're looking to upgrade to v3 and have been using your v1 provider up until now - which was much appreciated!

Thanks,

Ian
