### ISSUE TITLE
идея

### ISSUE THREAD

**Issue by vinnitu** [andrew-makarenko/botbuilder-facebook#3]
доброго времени суток

могу ли я поинтересоваться в чем состоит суть этого модуля?
мне показалось что здесь нет соедиениея app<->microsoft или так и есть?
т.е. общение с фейсбук идет непосредственно app<->fb

**Comment by andrew-makarenko** [comment]
доброго!
абсолютно верно, эта библиотека позволяет работать непосредственно с фб.

**Comment by vinnitu** [comment]
Андрей, а какая цель преследовалась? Что мы таким образом выигрываем?

**Comment by andrew-makarenko** [comment]
Here are some reasons why to use botbuilder-facebook connector instead of MS botbuilder connector service:
1. + Latency
2. Full control of data being transferred.
3. You (and facebook) are in charge of your uptime.
