### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by cesarvarela** [andrew-makarenko/botbuilder-facebook#4]
Hey, nice work! We weren't sure doing something likes this would be "possible"

- How did you do you? Just reverse engineering or there si some doc out there?
- Does this keep all the features of MS original connector? Like stateless convos, etc.

thanks!

**Comment by andrew-makarenko** [comment]
Hello!
Well, I haven't seen a documentation about it, but the classes hierarchy in the botbuilder is pretty straightforward and could be extended with ease, just need to spend some time reading their code.
It keeps all the features of MS connector.
This library is just an adapter, it allows to create a facebook bots without using the botbuilder connector service.

**Important note**: This library uses the botbuilder v1.* framework, which is kind of old. Unfortunately I don't have time to migrate to botbuilder v3+.

Let me know if you have any questions

**Comment by andrew-makarenko** [comment]
Consider using [Botkit](https://github.com/howdyai/botkit) instead of this library

**Comment by cesarvarela** [comment]
Yes, we'll use botkit for now, but we like botframework's architecture better (stateless, etc.)

Thanks for the detailed response.
